# Generated by Django 5.0 on 2024-01-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_participant_address_alter_participant_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='expert_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='account/media'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='last_checked_competition',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
