# Generated by Django 5.0 on 2024-01-05 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_expert_about_alter_expert_expert_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='expert_token',
        ),
    ]
