# Generated by Django 5.0 on 2023-12-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='advantages/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'advantage',
                'verbose_name_plural': 'advantages',
                'db_table': 'advantages',
            },
        ),
    ]
