# Generated by Django 5.0 on 2024-01-06 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0002_initial'),
        ('competition', '0001_initial'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionmodel',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.expert'),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.region'),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competitionmodel'),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.participant'),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.region', to_field='name'),
        ),
    ]
