# Generated by Django 5.0 on 2023-12-30 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
        ('account', '0001_initial'),
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.expert'),
        ),
        migrations.AddField(
            model_name='result',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.questionnairemodel'),
        ),
    ]
