# Generated by Django 5.0.1 on 2024-01-09 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
        ('competition', '0001_initial'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.expert'),
        ),
        migrations.AddField(
            model_name='result',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.questionnairemodel'),
        ),
    ]
