# Generated by Django 4.2.2 on 2023-12-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=100, unique=True)),
                ('img', models.ImageField(upload_to='criteria/')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'counter',
                'verbose_name_plural': 'counters',
                'db_table': 'counter',
            },
        ),
    ]
